import User from "../models/User.model.js";
import { ROLES, STATUS } from "../config/constants.js";
import { generatePassword } from "../utils/password.utils.js";

/**
 * Returns a paginated, filtered list of users.
 */
export const getAllUsers = async ({ page = 1, limit = 10, role, status, search }) => {
  const query = {};

  if (role) query.role = role;
  if (status) query.status = status;
  if (search) {
    query.$or = [
      { name: { $regex: search, $options: "i" } },
      { email: { $regex: search, $options: "i" } },
    ];
  }

  const skip = (page - 1) * limit;
  const total = await User.countDocuments(query);

  const users = await User.find(query)
    .populate("createdBy", "name email")
    .populate("updatedBy", "name email")
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(Number(limit))
    .lean();

  return {
    users,
    pagination: {
      total,
      page: Number(page),
      limit: Number(limit),
      totalPages: Math.ceil(total / limit),
    },
  };
};

/**
 * Returns a single user by ID.
 */
export const getUserById = async (id) => {
  const user = await User.findById(id)
    .populate("createdBy", "name email")
    .populate("updatedBy", "name email");

  if (!user) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }

  return user.toPublicJSON();
};

/**
 * Admin creates a new user, optionally auto-generating a password.
 */
export const createUser = async (data, adminId) => {
  const { name, email, role = ROLES.USER, status = STATUS.ACTIVE } = data;
  let { password } = data;

  let autoGenerated = false;
  if (!password) {
    password = generatePassword();
    autoGenerated = true;
  }

  const existing = await User.findOne({ email });
  if (existing) {
    const err = new Error("An account with that email already exists.");
    err.statusCode = 409;
    throw err;
  }

  const user = await User.create({
    name,
    email,
    password,
    role,
    status,
    createdBy: adminId,
    updatedBy: adminId,
  });

  const result = user.toPublicJSON();
  // Return the raw password only once, immediately after creation
  if (autoGenerated) result.generatedPassword = password;

  return result;
};

/**
 * Admin updates any user.
 */
export const updateUser = async (id, data, actorId, actorRole) => {
  const user = await User.findById(id);
  if (!user) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }

  // Managers cannot update admins
  if (actorRole === ROLES.MANAGER && user.role === ROLES.ADMIN) {
    const err = new Error("Managers cannot modify admin accounts.");
    err.statusCode = 403;
    throw err;
  }

  const allowedFields = ["name", "email", "status"];
  // Only admins can change roles
  if (actorRole === ROLES.ADMIN) allowedFields.push("role");

  allowedFields.forEach((field) => {
    if (data[field] !== undefined) user[field] = data[field];
  });

  user.updatedBy = actorId;
  await user.save();

  return user.toPublicJSON();
};

/**
 * User updates their own profile (name, password only).
 */
export const updateOwnProfile = async (id, data, actorId) => {
  const user = await User.findById(id).select("+password");
  if (!user) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }

  if (data.name) user.name = data.name;
  if (data.password) user.password = data.password;
  user.updatedBy = actorId;

  await user.save();
  return user.toPublicJSON();
};

/**
 * Soft-deletes (deactivates) a user. Only admins can do this.
 */
export const deactivateUser = async (id, adminId) => {
  const user = await User.findById(id);
  if (!user) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }

  if (user.role === ROLES.ADMIN) {
    const err = new Error("Admin accounts cannot be deactivated.");
    err.statusCode = 403;
    throw err;
  }

  user.status = STATUS.INACTIVE;
  user.updatedBy = adminId;
  await user.save();

  return user.toPublicJSON();
};

/**
 * Permanently deletes a user.
 */
export const deleteUser = async (id, adminId) => {
  const user = await User.findById(id);
  if (!user) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }

  // Prevent deleting yourself
  if (user._id.toString() === adminId.toString()) {
    const err = new Error("You cannot delete your own account.");
    err.statusCode = 403;
    throw err;
  }

  // Prevent deleting admin accounts
  if (user.role === ROLES.ADMIN) {
    const err = new Error("Admin accounts cannot be deleted.");
    err.statusCode = 403;
    throw err;
  }

  await User.findByIdAndDelete(id);
  return true;
};
